CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
	BOARD_TITLE VARCHAR2(500) NOT NULL,
	BOARD_CONTENT VARCHAR2(1000) NOT NULL,
	BOARD_REGISTER_DATE DATE,
	BOARD_UPDATE_DATE DATE,
	USER_ID NUMBER NOT NULL,
	CONSTRAINT FK_BOARD_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
	ON DELETE CASCADE
);

SELECT * 
FROM TBL_BOARD tb;

/*게시글 추가*/
INSERT INTO TBL_BOARD
(BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE, USER_ID)
VALUES(SEQ_BOARD.NEXTVAL, '', '', SYSDATE, SYSDATE, 0);

/*게시글 조회*/
SELECT BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE, USER_ID, USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_NICKNAME, USER_EMAIL, USER_ADDRESS, USER_BIRTH, USER_GENDER, USER_RECOMMENDER_ID 
FROM TBL_USER tu  JOIN TBL_BOARD tb 
ON TU.USER_ID = TB.USER_ID AND BOARD_ID = ?;

SELECT USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_NICKNAME, USER_EMAIL, USER_ADDRESS, USER_BIRTH, USER_GENDER, USER_RECOMMENDER_ID
FROM TBL_USER;

/*게시글 수정*/
UPDATE HR.TBL_BOARD
SET BOARD_TITLE='', BOARD_CONTENT='', BOARD_REGISTER_DATE= SYSDATE, BOARD_UPDATE_DATE= SYSDATE 
WHERE BOARD_ID=0;
 
/*게시글 삭제*/
DELETE FROM HR.TBL_BOARD
WHERE BOARD_ID=0;

/*게시글 전체 조회*/
SELECT BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_REGISTER_DATE,
				+ " BOARD_UPDATE_DATE, U.USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD,
				+ " USER_PHONE, USER_NICKNAME, USER_EMAIL, USER_ADDRESS, USER_BIRTH, USER_GENDER,
				+ " USER_RECOMMENDER_ID
				+ "FROM TBL_USER U JOIN TBL_BOARD B 
FROM TBL_USER U JOIN TBL_BOARD B 
ON U.USER_ID =B.USER_ID;
