CREATE SEQUENCE SEQ_USER;

/*회원번호, 아이디, 이름, 비밀번호, 전화번호, 닉네임, 이메일, 주소, 생년월일, 성별, 추천인 아이디*/
CREATE TABLE TBL_USER(
	USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_PASSWORD VARCHAR2(500) NOT NULL,
	USER_PHONE VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(500),
	USER_EMAIL VARCHAR2(100) CONSTRAINT UK_USER UNIQUE NOT NULL,
	USER_ADDRESS VARCHAR2(500),
	USER_BIRTH DATE,
	USER_GENDER CHAR(1) DEFAULT 'N' CHECK(USER_GENDER IN('M', 'W', 'N')),
	USER_RECOMMENDER_ID VARCHAR2(500)
);

INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS)
VALUES(SEQ_USER.NEXTVAL, 'korea7403', '김욱성', '1234', '01012341234', 'kus1234@gmail.com','서울송파');

INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS,USER_RECOMMENDER_ID)
VALUES(SEQ_USER.NEXTVAL, 'korea7402', '김성욱', '4567', '01043214321', 'ksu1234@gmail.com','서울잠실','korea1234');

INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS,USER_RECOMMENDER_ID)
VALUES(SEQ_USER.NEXTVAL, 'korea1234', '김욱', '6789', '01098769876', 'ku4567@gmail.com','서울역삼','korea1234');

DROP SEQUENCE SEQ_USER;
DROP TABLE TBL_USER;

--RECOMMENDER가 KOREA7403인 사람들의 수를 구한다.
SELECT COUNT(USER_ID) 
FROM TBL_USER 
WHERE USER_RECOMMENDER_ID ='KOREA7403';

-- 나를 추천한 사람의 USER_NAME을 조회한다.
INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_NICKNAME, USER_EMAIL, USER_ADDRESS, USER_BIRTH, USER_GENDER, USER_RECOMMENDER_ID)
VALUES( , '', '', '', '', '', '', '', '', 'N', '');

SELECT *FROM TBL_USER tu ;

SELECT USER_NAME 
FROM TBL_USER  
WHERE USER_RECOMMENDER_ID ='korea1234';

--내가 추천한 //사람 
/*내가 추천한 // 사람*/

SELECT *FROM TBL_USER t 
WHERE USER_IDENTIFICATION = (SELECT USER_RECOMMENDER_ID FROM TBL_USER WHERE USER_IDENTIFICATION = ?);

/*핸드폰 번호로 찾기*/
SELECT USER_IDENTIFICATION FROM TBL_USER tu WHERE USER_PHONE ='01012341234';

/*비밀번호 변경*/
/*아이디,비밀번호*/
UPDATE TBL_USER SET USER_PASSWORD ='1234' WHERE USER_IDENTIFICATION ='korea7403';

UPDATE TBL_USERSET USER_IDENTIFICATION='', USER_NAME='', USER_PASSWORD='', USER_PHONE='', USER_NICKNAME='', USER_ADDRESS='', USER_GENDER='N' WHERE USER_ID ='1';
